# Generated by Django 5.2 on 2026-05-11 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CongestionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('level', models.FloatField(default=1.0)),
                ('source', models.CharField(default='query', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_name', models.CharField(max_length=255)),
                ('dest_name', models.CharField(max_length=255)),
                ('origin_lat', models.FloatField()),
                ('origin_lng', models.FloatField()),
                ('dest_lat', models.FloatField()),
                ('dest_lng', models.FloatField()),
                ('distance_km', models.FloatField()),
                ('duration_sec', models.FloatField()),
                ('route_geometry', models.JSONField()),
                ('vehicle_type', models.CharField(default='car', max_length=50)),
                ('toll_amount', models.FloatField(blank=True, null=True)),
                ('pricing_model', models.CharField(blank=True, max_length=20, null=True)),
                ('congestion_level', models.CharField(default='light', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TollCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_toll', models.FloatField()),
                ('multiplier', models.FloatField()),
                ('total_toll', models.FloatField()),
                ('pricing_model', models.CharField(max_length=20)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='toll', to='insights.trip')),
            ],
        ),
    ]
