# Generated by Django 6.0.5 on 2026-05-19 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_name', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('condition_type', models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('under_construction', 'Under Construction'), ('closed', 'Closed'), ('accident', 'Accident'), ('flooding', 'Flooding'), ('pothole', 'Pothole')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('report_count', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('verified', 'Verified'), ('resolved', 'Resolved')], default='reported', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
